samples: config/samples.tsv
contrasts: config/contrasts.tsv

# Read length. Used by STAR and rMATS
read_length: 80

# Download GTF, genome, and transcriptome (cDNA and ncRNA) data.
# You can either specify the full path to your local files or use the links to Ensembl's FTP server.
ref:
  gtf: resources/ensembl.homo_sapiens.GRCh38.112.snoDB.GtRNAdb.gtf
  dna_fasta: https://ftp.ensembl.org/pub/release-112/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  cdna_fasta: https://ftp.ensembl.org/pub/release-112/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
  ncrna_fasta: https://ftp.ensembl.org/pub/release-112/fasta/homo_sapiens/ncrna/Homo_sapiens.GRCh38.ncrna.fa.gz

salmon:
  activate: false

coco:
  activate: true

rmats:
  activate: true
  # Use the paired stats model (PAIRADISE)
  paired_stats: false

deseq2:
  activate: true
  # Full design formula (no spaces). Variables must match columns in the samples sheet.
  full_model: ~condition
  # Optional: Reduced design formula for likelihood ratio test (no spaces).
  # Set to `false` or leave empty if not used.
  reduced_model: ~1
  # Optional: Path to a file with one gene ID per line for size factor estimation. Set to `false` if not used.
  control_genes: false
  # Use TPM for filtering gene expression. Set to `false` to use raw counts.
  tpm: true
  # Minimum gene expression level.
  min_gene_expr: 1
  # Minimum number of samples in which a gene must be expressed.
  min_samps_gene_expr: 3
  # Significance threshold for adjusted p-values.
  padj: 0.05
  # Significance threshold for absolute log2 fold change.
  lfc: 1
