samples: config/samples.tsv
contrasts: config/contrasts.tsv

# Read length. Used by STAR and rMATS
read_length: 80

# Download gtf, genome and transcriptome (cdna and ncrna) from Ensembl.
ref:
  # ensembl species name
  species: homo_sapiens
  # ensembl release version
  release: "112"
  # genome build
  build: GRCh38
  # Custom gtf, genome and/or transcriptome overwrites other reference info above.
  # Use the full path or the relative path from the Snakemake directory.
  # Leave it empty if you want to download from Ensembl.
  custom_gtf: resources/ensembl.homo_sapiens.GRCh38.112.snoRNA_scaRNA_removed.snoDBv2.GtRNAdbv22.gtf
  custom_genome:
  custom_transcriptome:

salmon:
  activate: false

coco:
  activate: true

rmats:
  activate: true
  # Use the paired stats model (PAIRADISE)
  paired_stats: false

deseq2:
  activate: true
  # Full design formula (no spaces). Variables must match columns in the samples sheet.
  full_model: ~condition
  # Optional: Reduced design formula for likelihood ratio test (no spaces).
  # Set to `false` or leave empty if not used.
  reduced_model: ~1
  # Optional: Path to a file with one gene ID per line for size factor estimation. Set to `false` if not used.
  control_genes: false
  # Use TPM for filtering gene expression. Set to `false` to use raw counts.
  tpm: true
  # Minimum gene expression level.
  min_gene_expr: 1
  # Minimum number of samples in which a gene must be expressed.
  min_samps_gene_expr: 3
  # Significance threshold for adjusted p-values.
  padj: 0.05
  # Significance threshold for absolute log2 fold change.
  lfc: 1
