cluster:
  mkdir -p logs_slurm/{rule} &&
  bash profiles/slurm/slurm_submit.sh
  '--account=def-kchoquet
  --mail-user=louis-philippe.chaumont@usherbrooke.ca
  --mail-type=FAIL
  --job-name={rule}-{wildcards}
  --mem={resources.mem_gb}G
  --time={resources.time}
  --cpus-per-task={resources.threads}
  --output=logs_slurm/{rule}/%j-{wildcards}.log'
  '{rule}' '{wildcards}' '{dependencies}'


default-resources:
    - threads=1
    - mem_gb=1
    - time='0-1:00'


set-resources:
    fastp:
        threads: 3
        mem_gb: 4
        time: 0-0:30

    trimmomatic:
        threads: 4
        mem_gb: 2
        time: 0-1:00

    salmon_index:
        threads: 4
        mem_gb: 24
        time: 0-1:00

    salmon_quant:
        threads: 4
        mem_gb: 8
        time: 0-1:00

    star_index:
        threads: 8
        mem_gb: 48
        time: 0-2:00
    
    star_align:
        threads: 4
        mem_gb: 36
        time: 0-2:00

    sam_sort_by_name:
        threads: 32
        mem_gb: 8
        time: 0-3:00

    qualimap_bamqc:
        threads: 4
        mem_gb: 4
        time: 0-1:00

    qualimap_rnaseq:
        mem_gb: 16
        time: 0-1:00

    collapse_gtf:
        mem_gb: 3
        time: 0-0:30

    rnaseqc:
        mem_gb: 1
        time: 0-0:30

    coco_ca:
        mem_gb: 8
        time: 0-1:00

    coco_cc:
        threads: 4
        mem_gb: 36
        time: 0-12:00

    coco_cb:
        thread: 1
        mem_gb: 16
        time: 0-12:00

    coco_sort_bg:
        threads: 4
        mem_gb: 6
        time: 0-1:00

    rmats_prep:
        threads: 4
        mem_gb: 2
        time: 0-1:00


immediate-submit: True
jobs: 999 
use-conda: True
conda-frontend: mamba
use-envmodules: False
keep-going: True
notemp: True
printshellcmds: True
rerun-triggers: mtime
verbose: False
